### ISSUE TITLE
Rotate has issues animating well

### ISSUE THREAD

**Issue by Hoatzin** [louisremi/jquery.transform.js#24] opened 2012-04-02 22:17 UTC
http://jsfiddle.net/EvsVJ/ 

When you switch to the newer version of the plugin, css() works but the subsequent animate() does not. I have only noticed this wackiness when dealing with rotate—scaleX and translate (the other ones I have tried) have animated just fine.

**Comment by louisremi** [comment] 2012-04-03 09:57
Ok, the problem in your jsfiddle is that your animation is tarting and ending at equivalent angles (0 <=> 360 <=> 720 <=> -360 <=> ... ).

It is impossible to interpolate (or calculate each step of the animation) between two equivalent angles.
The solution to this problem is to use relative animation:

```
$(elem).css({transform: "rotate(45deg)"}).animate({transform: "+=rotate(360deg)"}).
```

I was able to fix you jsfiddle using this "+=" syntax.

I love hobolobo.net by the way. I'm very proud that you used my script in it.

**Comment by Hoatzin** [comment] 2012-04-03 15:38
I am glad I can provide such an over-the-top proving grounds for your plugin :) It is really the only thing of its kind out there that works! Thanks for making it, I owe you a beer. Or a CD. Do you actually listen to physical media?

So, ok—that would fix that one. Still, 0° and 360° are different angles, it is intuitive that it should work, and the behavior was supported in the older version... Though it is not that big a deal in this case.

There is another issue with rotation—which I thought would be fixed if the first one was—and it could yet be the same issue (i.e. I have no idea what I am writing or the methodology of the plugin evolved):

I have tweaked this jsfiddle chunk of code to use .scrollTop() as opposed the .scrollLeft() that Hobo Lobo natively relies on—because jsfiddle wouldn't let me make a wide page for some reason—but I have left the var names with their 'left' and 'right' as in the original code. The function is supposed to animate relative to the scroll—at the left/top limit and beyond, the value of whatever property should be A and at the right/bottom and beyond it should be B and in between it is linearly figured out relative to the scrollLeft/scrollTop. This function handles the rotating fir tops in http://hobolobo.net/tale/3#c_9 for example.

This is it with the light version:
http://jsfiddle.net/e225x/1/

Rotation works smoothly, but the scaleY is scaling both axes in weird ways. Getting this behavior normalized is the primary reason I am updating the plugin.

This is the same code with the new 2d:
http://jsfiddle.net/e225x/

The scaleY behaves as I would expect it to, but now rotate is being weird and chuggy. If you replace the rotate with skew, it works fine.

**Comment by louisremi** [comment] 2012-04-04 09:13
Hey @Hoatzin,

I just pushed a fix that solves your problem.
It probably had to do with the fact that I wasn't rounding values anymore, which happens to be a bad idea.

And yes, I listen to physical media, every so often on my hi-fi. Most of the time I listen to digitalized tracks but I'm really attached to their box, their cover-art, their leaflet. And I think good music and good art deserve to be paid for.

**Comment by louisremi** [comment] 2012-04-04 11:56
I forget to explain why animating from 0° to 360° doesn't work anymore:
The light version used to keep track internally of the transforms applied to an element, so it was able to handle that case.

Recently I decided to create a plugin for 3d transforms. I wanted to leverage CSS3 Transitions to achieve animations (because animating 3d transforms is too complex for JS) and I wanted the 2d and 3d plugins to behave in the same way. So I had to change the interpolation algorithm of the 2d plugin to match what the w3c spec defines for 2d and 3d transforms transitions. And this spec prevents (for good reason that are too long to explain) to keep track of the transforms of an element.

I'm not sure if my explanation was really clear but my point is: this regression is not a bug, it HAD to be that way.

**Comment by Hoatzin** [comment] 2012-04-04 14:28
Ok, I believe you :) I figured reasons existed. The only concern from where I am standing is the potential unintuitiveness to peeps like me who've done simple rotations in Flash or something like it. Maybe all that is needed here is a line to the effect in the README.

Thanks for fixing the bug! Is your wishlist current? Is there anything on that list that would really scratch an itch right about now or can I take my pick?

**Comment by louisremi** [comment] 2012-04-04 15:52
You're right that it should be mentioned in the documentation. But the '+=' syntax actually doesn't work with the 3d transform plugin, because of a limitation in the spec. I've just sent an email to the w3 working group to see if that limitation could be removed.

My wishlist is always up to date and receiving CDs from "happy customers" is always really appreciated. If you find something that matches your tastes, go for it.

**Closed as completed by louisremi** 2012-04-04 15:52 UTC
