### ISSUE TITLE
Need to set transform-origin

### ISSUE THREAD

**Issue by smartinec** [louisremi/jquery.transform.js#17] opened 2011-10-24 22:53 UTC
How can I set the "transform-origin" property?

**Comment by louisremi** [comment] 2011-10-25 08:41
I should write documentation about this.
The idea is to wrap the element or elements you want to transform in a div, and use the center of this div as a transform-origin for your elements.
Here's an example: http://jsfiddle.net/louisremi/jCw23/4/

**Comment by smartinec** [comment] 2011-10-25 11:24
I'm not sure that works for my use case. I'm scaling iframes and stacking them side by side. I found another plugin based off your code that supports it.

**Comment by louisremi** [comment] 2011-10-25 11:36
Which plugin?
Could you show me what you are trying to achieve (the end result with the other lib)?

**Comment by smartinec** [comment] 2011-10-25 12:09
https://github.com/puppybits/QTransform

I don't yet have the code on a public site, but I am loading multiple iFrames with different webpages and scaling them to 0.8. I put 3 right next to each other so they span the screen and they are the full browser height. If I don't set transform-origin to '0 0' the scroll bars don't show and the iFrames are offset from where I need them to be.

**Comment by louisremi** [comment] 2011-10-25 12:30
Interesting, I'll have a closer look at his code.

**Comment by louisremi** [comment] 2012-01-25 11:47
I'll soon have a branch for transformOrigin, I'm closing this issue as it's a duplicate of heygrady's PR.

**Closed as completed by louisremi** 2012-01-25 11:47 UTC
